using System;

namespace SevenEngine
{
  // THIS CLASS IS NOT YET IN DEVELOPMENT.
  // ITS DEVELOPMENT CANNOT BEGIN UNTIL THERE IS A WORKING OCTREE DATA STRUCTURE.
  // THE OCTREE IS NEEDED FOR EFFICIENT COLLISION DETECTION.
  public class PhysicsManager
  {
  }
}